version: "3.9"

services:
  telegram-bot:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db-devquiz
  db-devquiz:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db-devquiz
    volumes:
      - "./db-devquiz/dbdata:/var/lib/postgresql/data"
    command: "-c log_statement=all" 